language: node_js
node_js:
    - 13
    - 12
    - 10

cache:
  npm: false

matrix:
    allow_failures:
        - os: windows

os:
    - linux
    - osx
    - windows

# https://docs.travis-ci.com/user/customizing-the-build/#git-end-of-line-conversion-control
# need for windows
git:
  autocrlf: input

script:
  - npm i cross-env -g
  - npm run lint && cross-env npm run build && npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: required

services:
  - docker

deploy:
    provider: script
    script: npm run docker-ci
    skip_cleanup: true
    on:
        node: '10'
        condition: $TRAVIS_OS_NAME = linux
        tags: true
        all_branches: false

